<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class MaterialsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $currentTime = Carbon::now();
        $data = [
            [
                'title' => 'Principles of General Chemistry',
                'category_id' => 1,
                'isbn' => 'ISBN 978-07-131798-6',
                'callno' => 'QD 31.3 S55 2013',
                'author' => 'Silberberg',
                'publisher' => 'McGraw Hill Company Inc.',
                'edition' => '1st Edition',
                'copyright' => '2013',
                'status' => 1,
                'type' => 1,
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'deleted_at' => NULL
            ],
            [
                'title' => 'The Professional Approach: Microsoft Office 2007',
                'category_id' => 1,
                'isbn' => 'ISBN 978-0-07-337351-5',
                'callno' => 'a',
                'author' => 'Hinkle, Graves, Juarez, Stewart, Mayhall, Carter,',
                'publisher' => 'The McGraw-Hill Companies, Inc.',
                'edition' => '3rd Edition',
                'copyright' => '2007',
                'status' => 1,
                'type' => 1,
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'deleted_at' => NULL
            ],
            [
                'title' => 'Financial and Managerial Accounting',
                'category_id' => 1,
                'isbn' => 'ISBN 978-0-07-352699-7',
                'callno' => 'a',
                'author' => 'Jan Williams, Sue Haka, Mark Bettner,Joseph Carcel',
                'publisher' => 'The McGraw-Hill Companies, Inc.',
                'edition' => '2nd Edition',
                'copyright' => '2018',
                'status' => 1,
                'type' => 1,
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'deleted_at' => NULL
            ],
            [
                'title' => 'Programming with Microsoft : Visual Basic 2012',
                'category_id' => 1,
                'isbn' => 'ISBN-13: 978-1-285-07792-5',
                'callno' => 'QA 76.76 B3z3374 2014',
                'author' => 'Diane Zak',
                'publisher' => 'CENGAGE Learning Asia',
                'edition' => '6th Edition',
                'copyright' => NULL,
                'status' => 1,
                'type' => 1,
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'deleted_at' => NULL
            ],
            [
                'title' => 'Foundation of Finance',
                'category_id' => 1,
                'isbn' => 'ISBN-13: 978-0-13-512236-5',
                'callno' => 'HG 4026.F67 K46 2011',
                'author' => 'Keown , Martin, Petty',
                'publisher' => 'Pearson Education',
                'edition' => NULL,
                'copyright' => NULL,
                'status' => 1,
                'type' => 1,
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'deleted_at' => NULL
            ],
            [
                'title' => 'Cost Accounting : A Managerial Emphasis',
                'category_id' => 1,
                'isbn' => 'ISBN-13: 978-0-273-77985-5',
                'callno' => 'Hf 5586.C8 H59 2012',
                'author' => 'Charles T. Horngren, Srikant M. Datar, Madhav V. R',
                'publisher' => 'Pearson Education Limited Inc.',
                'edition' => NULL,
                'copyright' => NULL,
                'status' => 1,
                'type' => 1,
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'deleted_at' => NULL
            ],
            [
                'title' => 'Financial and Managerial Accounting',
                'category_id' => 1,
                'isbn' => 'ISBN 0-07-123016-5',
                'callno' => 'HF5635.M492',
                'author' => 'Williams, Haka, Bettner, Meigs',
                'publisher' => 'The McGraw-Hill Companies, Inc.',
                'edition' => NULL,
                'copyright' => NULL,
                'status' => 1,
                'type' => 1,
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'deleted_at' => NULL
            ],
            [
                'title' => 'Mastering ArcGIS',
                'category_id' => 1,
                'isbn' => 'ISBN 978-0-07-352284-5',
                'callno' => 'G70.212.P74',
                'author' => 'Maribeth Price',
                'publisher' => 'The McGraw-Hill Companies, Inc.',
                'edition' => NULL,
                'copyright' => NULL,
                'status' => 1,
                'type' => 1,
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'deleted_at' => NULL
            ],
            [
                'title' => 'Starting out with C++ Early Objects',
                'category_id' => 1,
                'isbn' => 'ISBN-13: 978-0-321-52678-6',
                'callno' => 'QA 76.73 C153G123 2007',
                'author' => 'Tony Gaddis, Judy Walters, Godfrey Muganda',
                'publisher' => 'Pearson Education, Inc',
                'edition' => NULL,
                'copyright' => NULL,
                'status' => 1,
                'type' => 1,
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'deleted_at' => NULL
            ],
            [
                'title' => 'Visualization, Modeling, and Graphics for Engineer',
                'category_id' => 1,
                'isbn' => 'ISBN-13: 978-1-4018-4251-2',
                'callno' => 'TA 174 L721',
                'author' => 'Lieu/Sorby',
                'publisher' => 'CENGAGE Learning Asia',
                'edition' => NULL,
                'copyright' => NULL,
                'status' => 1,
                'type' => 1,
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'deleted_at' => NULL
            ],
            [
                'title' => 'Introduction to Digital Electronics',
                'category_id' => 1,
                'isbn' => 'ISBN-13: 978-1-4180-4102-1',
                'callno' => 'TK 7868.D5 R353',
                'author' => 'Ken Reid, Robert Dueck',
                'publisher' => 'Thomson Delmar Learning',
                'edition' => NULL,
                'copyright' => NULL,
                'status' => 1,
                'type' => 1,
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'deleted_at' => NULL
            ],
            [
                'title' => 'Workbook for Technology of Machine Tools',
                'category_id' => 1,
                'isbn' => 'ISBN-13: 978-0-07-830724-9',
                'callno' => 'REF 621902 K864T',
                'author' => 'Steve F. Krar, Arthur R. Gill, Peter Smid',
                'publisher' => 'McGraw Hill Company Inc.',
                'edition' => NULL,
                'copyright' => NULL,
                'status' => 1,
                'type' => 1,
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'deleted_at' => NULL
            ],
            [
                'title' => 'Computer Concepts: Introductory',
                'category_id' => 1,
                'isbn' => 'ISBN-13: 978-1-4239-0609-4',
                'callno' => 'QA 76 P269',
                'author' => 'June Jamrich Parsons, Dan Oja',
                'publisher' => 'Thomson Course Technology',
                'edition' => NULL,
                'copyright' => NULL,
                'status' => 1,
                'type' => 1,
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'deleted_at' => NULL
            ],
            [
                'title' => 'Refrigeration and Air Conditioning Technology',
                'category_id' => 1,
                'isbn' => 'ISBN-13: 978-1-4283-1936-3',
                'callno' => 'TP 492 R281',
                'author' => NULL,
                'publisher' => NULL,
                'edition' => NULL,
                'copyright' => NULL,
                'status' => 1,
                'type' => 1,
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'deleted_at' => NULL
            ],
            [
                'title' => 'Automotive Service',
                'category_id' => 1,
                'isbn' => 'ISBN-13: 978-1-4180-3758-1',
                'callno' => 'TL 152 G472',
                'author' => 'Tim Gilles',
                'publisher' => 'DELMAR CENGAGE Learning',
                'edition' => NULL,
                'copyright' => NULL,
                'status' => 1,
                'type' => 1,
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'deleted_at' => NULL
            ],
            [
                'title' => 'JAVA How to Program',
                'category_id' => 1,
                'isbn' => 'ISBN 0-13-6134247-2',
                'callno' => 'QA 76.73 J38D325',
                'author' => NULL,
                'publisher' => NULL,
                'edition' => NULL,
                'copyright' => NULL,
                'status' => 1,
                'type' => 1,
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'deleted_at' => NULL
            ],
            [
                'title' => 'JAVA Learning to Program with Robots',
                'category_id' => 1,
                'isbn' => 'ISBN 0-619-21724-3',
                'callno' => 'QA 76.73 J38B395',
                'author' => NULL,
                'publisher' => NULL,
                'edition' => NULL,
                'copyright' => NULL,
                'status' => 1,
                'type' => 1,
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'deleted_at' => NULL
            ],
            [
                'title' => 'Programming Logic and Design: Comprehensive',
                'category_id' => 1,
                'isbn' => 'ISBN-13: 978-1-4239-0196-9',
                'callno' => 'QA 76,73 F245',
                'author' => NULL,
                'publisher' => NULL,
                'edition' => NULL,
                'copyright' => NULL,
                'status' => 1,
                'type' => 1,
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'deleted_at' => NULL
            ],
            [
                'title' => 'Microsoft Visual Basic 2005: BASICS',
                'category_id' => 1,
                'isbn' => 'ISBN-13: 978-0-619-26720-9',
                'callno' => 'QA 76.73 B3M626',
                'author' => NULL,
                'publisher' => NULL,
                'edition' => NULL,
                'copyright' => NULL,
                'status' => 1,
                'type' => 1,
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'deleted_at' => NULL
            ],
            [
                'title' => 'Wastewater Engineering: Treatment and Reuse',
                'category_id' => 1,
                'isbn' => 'ISBN 0-07-253855-4',
                'callno' => NULL,
                'author' => NULL,
                'publisher' => NULL,
                'edition' => NULL,
                'copyright' => NULL,
                'status' => 1,
                'type' => 1,
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'deleted_at' => NULL
            ],
            [
                'title' => 'Student Solutions Manual to Accompany Chemistry:  The Molecular Nature of Matter and Change',
                'category_id' => 1,
                'isbn' => 'ISBN 978-0-07-304860-4',
                'callno' => 'QD33.2 S55',
                'author' => 'Patricia Amateis, Martin S. Silberberg',
                'publisher' => 'The McGraw-Hill Companies, Inc.',
                'edition' => '5th Edition',
                'copyright' => '2006',
                'status' => 1,
                'type' => 1,
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'deleted_at' => NULL
            ],
            [
                'title' => 'Problem-Solving Cases in Microsoft Access and Excel',
                'category_id' => 1,
                'isbn' => 'ISBN 1-4188-3706-7',
                'callno' => 'HF 5548 M525B798',
                'author' => 'Joseph A. Brady, Ellen F. Monk',
                'publisher' => 'Thomson Course Technology',
                'edition' => '4th Edition',
                'copyright' => '2007',
                'status' => 1,
                'type' => 1,
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'deleted_at' => NULL
            ],
            [
                'title' => 'Fundamentals of Information Systems',
                'category_id' => 1,
                'isbn' => 'ISBN-13a978-1-4239-0117-4',
                'callno' => 'T 58.6 s782',
                'author' => 'Ralph Stair, George Reynolds',
                'publisher' => 'Thomson Course Technology',
                'edition' => '4th Edition',
                'copyright' => '2008',
                'status' => 1,
                'type' => 1,
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'deleted_at' => NULL
            ],
            [
                'title' => 'CompTIA A+ Guide to Software: Managing, Maintaining, Troubleshooting',
                'category_id' => 1,
                'isbn' => 'ISBN-13: 978-0-619-21760-0',
                'callno' => 'QA 76.3 A567',
                'author' => 'Jean Andrews',
                'publisher' => 'Thomson Course Technology',
                'edition' => '4th Edition',
                'copyright' => '2007',
                'status' => 1,
                'type' => 1,
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'deleted_at' => NULL
            ],
            [
                'title' => 'Thomson Course Technology',
                'category_id' => 1,
                'isbn' => 'ISBN-13: 978-0-9778582-3-1',
                'callno' => 'ISBN-13: 978-0-9778582-3-1',
                'author' => 'M. Tim Jones',
                'publisher' => 'Infinity Science Press',
                'edition' => '1st Edition',
                'copyright' => '2008',
                'status' => 1,
                'type' => 1,
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'deleted_at' => NULL
            ],
            [
                'title' => 'Infinity Science Press',
                'category_id' => 1,
                'isbn' => 'ISBN-13: 978-0-9778582-3-1',
                'callno' => 'Q 336 J78 2008',
                'author' => 'M. Tim Jones',
                'publisher' => 'Infinity Science Press',
                'edition' => '1st Edition',
                'copyright' => '2008',
                'status' => 1,
                'type' => 1,
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'deleted_at' => NULL
            ],
            [
                'title' => 'Fundamentals of Microcontrollers and Applications in Embedded Systems(with the PIC 18 Microcontroller Family)',
                'category_id' => 1,
                'isbn' => 'ISBN-13: 978-0-9778582-3-1',
                'callno' => 'TJ 223 G111',
                'author' => 'Ramesh S. Gaonkar',
                'publisher' => 'Thomson Delmar Learning',
                'edition' => NULL,
                'copyright' => '2007',
                'status' => 1,
                'type' => 1,
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'deleted_at' => NULL
            ],
            [
                'title' => 'Managing Interactive Media Projects',
                'category_id' => 1,
                'isbn' => 'ISBN-13: 978-1-4180-5001-6',
                'callno' => 'QA 76.76 T59F897',
                'author' => 'Tim Frick',
                'publisher' => 'Thomson Delmar Learning',
                'edition' => NULL,
                'copyright' => '2008',
                'status' => 1,
                'type' => 1,
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'deleted_at' => NULL
            ],
            [
                'title' => 'An Introduction to PROGRAMMING Using VISUAL BASIC 2008',
                'category_id' => 1,
                'isbn' => 'ISBN-13: 978-0-13-606072-7',
                'callno' => 'QA 76.73 B3S358',
                'author' => 'David I. Schneider',
                'publisher' => 'Pearson Prentice Hall',
                'edition' => '7th Edition',
                'copyright' => '2009',
                'status' => 1,
                'type' => 1,
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'deleted_at' => NULL
            ],
            [
                'title' => 'The Art of Watching Films',
                'category_id' => 1,
                'isbn' => 'ISBN 978-0-07-353507-4',
                'callno' => 'PN1995 B525',
                'author' => 'Joseph M. Boggs, Dennis W. Petrie',
                'publisher' => 'McGraw Hill Company Inc.',
                'edition' => '7th Edition',
                'copyright' => '2008',
                'status' => 1,
                'type' => 1,
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'deleted_at' => NULL
            ],
            [
                'title' => 'Fundamentals of Applied Electromagnetics',
                'category_id' => 1,
                'isbn' => 'ISBN 0-13-229630-6',
                'callno' => 'QC 760 U36',
                'author' => NULL,
                'publisher' => NULL,
                'edition' => NULL,
                'copyright' => NULL,
                'status' => 1,
                'type' => 1,
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'deleted_at' => NULL
            ],
            
        ];
        
        DB::table('materials')->insert($data);
    }
}
