<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserLinksSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => 1,
                'link_name' => 'List of Users',
                'slug_name' => 'User.index',
                'parent_link_id' => 1,
                'display_status' => 1,
            ],
            [
                'id' => 2,
                'link_name' => 'Add User',
                'slug_name' => 'User.store',
                'parent_link_id' => 1,
                'display_status' => 0,
            ],
            [
                'id' => 3,
                'link_name' => 'Edit User',
                'slug_name' => 'User.show',
                'parent_link_id' => 1,
                'display_status' => 0,
            ],
            [
                'id' => 4,
                'link_name' => 'Delete User',
                'slug_name' => 'UserDelete',
                'parent_link_id' => 1,
                'display_status' => 0,
            ],
            [
                'id' => 5,
                'link_name' => 'List of Roles',
                'slug_name' => 'Roles.index',
                'parent_link_id' => 1,
                'display_status' => 1,
            ],
            [
                'id' => 6,
                'link_name' => 'Add Roles',
                'slug_name' => 'Roles.store',
                'parent_link_id' => 1,
                'display_status' => 0,
            ],
            [
                'id' => 7,
                'link_name' => 'Edit Roles',
                'slug_name' => 'Roles.show',
                'parent_link_id' => 1,
                'display_status' => 0,
            ],
            [
                'id' => 8,
                'link_name' => 'Delete Roles',
                'slug_name' => 'RolesDelete',
                'parent_link_id' => 1,
                'display_status' => 0,
            ],
            [
                'id' => 9,
                'link_name' => 'List of Courses',
                'slug_name' => 'Course.index',
                'parent_link_id' => 1,
                'display_status' => 1,
            ],
            [
                'id' => 10,
                'link_name' => 'Add Courses',
                'slug_name' => 'Course.store',
                'parent_link_id' => 1,
                'display_status' => 0,
            ],
            [
                'id' => 11,
                'link_name' => 'Edit Courses',
                'slug_name' => 'Course.show',
                'parent_link_id' => 1,
                'display_status' => 0,
            ],
            [
                'id' => 12,
                'link_name' => 'Delete Courses',
                'slug_name' => 'CourseDelete',
                'parent_link_id' => 1,
                'display_status' => 0,
            ],
            [
                'id' => 13,
                'link_name' => 'Genders',
                'slug_name' => 'Gender.index',
                'parent_link_id' => 1,
                'display_status' => 1,
            ],
            [
                'id' => 14,
                'link_name' => 'Add Gender',
                'slug_name' => 'Gender.store',
                'parent_link_id' => 1,
                'display_status' => 0,
            ],
            [
                'id' => 15,
                'link_name' => 'Edit Gender',
                'slug_name' => 'Gender.show',
                'parent_link_id' => 1,
                'display_status' => 0,
            ],
            [
                'id' => 16,
                'link_name' => 'Delete Gender',
                'slug_name' => 'GenderDelete',
                'parent_link_id' => 1,
                'display_status' => 0,
            ],
            [
                'id' => 17,
                'link_name' => 'Permissions',
                'slug_name' => 'Permissions.index',
                'parent_link_id' => 1,
                'display_status' => 1,
            ],
            [
                'id' => 18,
                'link_name' => 'Add Permission',
                'slug_name' => 'Permissions.create',
                'parent_link_id' => 1,
                'display_status' => 0,
            ],
            [
                'id' => 19,
                'link_name' => 'Edit Permission',
                'slug_name' => 'Permissions.show',
                'parent_link_id' => 1,
                'display_status' => 0,
            ],
            [
                'id' => 21,
                'link_name' => 'List of Materials',
                'slug_name' => 'Material.index',
                'parent_link_id' => 2,
                'display_status' => 1,
            ],
            [
                'id' => 22,
                'link_name' => 'Add Materials',
                'slug_name' => 'Material.store',
                'parent_link_id' => 2,
                'display_status' => 0,
            ],
            [
                'id' => 23,
                'link_name' => 'Edit Materials',
                'slug_name' => 'Material.show',
                'parent_link_id' => 2,
                'display_status' => 0,
            ],
            [
                'id' => 24,
                'link_name' => 'Delete Materials',
                'slug_name' => 'MaterialsDelete',
                'parent_link_id' => 2,
                'display_status' => 0,
            ],
            [
                'id' => 25,
                'link_name' => 'Materials Category',
                'slug_name' => 'MaterialsCategory.index',
                'parent_link_id' => 2,
                'display_status' => 1,
            ],
            [
                'id' => 26,
                'link_name' => 'Add Materials Category',
                'slug_name' => 'MaterialsCategory.store',
                'parent_link_id' => 2,
                'display_status' => 0,
            ],
            [
                'id' => 27,
                'link_name' => 'Edit Materials Category',
                'slug_name' => 'MaterialsCategory.show',
                'parent_link_id' => 2,
                'display_status' => 0,
            ],
            [
                'id' => 28,
                'link_name' => 'Delete Materials Category',
                'slug_name' => 'MaterialsCategoryDelete',
                'parent_link_id' => 2,
                'display_status' => 0,
            ],
            [
                'id' => 29,
                'link_name' => 'Materials Subject',
                'slug_name' => 'MaterialsSubject.index',
                'parent_link_id' => 2,
                'display_status' => 1,
            ],
            [
                'id' => 30,
                'link_name' => 'Add Materials Subject',
                'slug_name' => 'MaterialsSubject.store',
                'parent_link_id' => 2,
                'display_status' => 0,
            ],
            [
                'id' => 31,
                'link_name' => 'Edit Materials Subject',
                'slug_name' => 'MaterialsSubject.show',
                'parent_link_id' => 2,
                'display_status' => 0,
            ],
            [
                'id' => 32,
                'link_name' => 'Delete Materials Subject',
                'slug_name' => 'MaterialsSubjectDelete',
                'parent_link_id' => 2,
                'display_status' => 0,
            ],

            // Issuing of Books
            [
                'id' => 33,
                'link_name' => 'Borrowed Books',
                'slug_name' => 'Issuing.index',
                'parent_link_id' => 3,
                'display_status' => 1,
            ],
            [
                'id' => 34,
                'link_name' => 'Add Issuing Of Books',
                'slug_name' => 'Issuing.store',
                'parent_link_id' => 3,
                'display_status' => 0,
            ],
            [
                'id' => 35,
                'link_name' => 'Edit Issuing Of Books',
                'slug_name' => 'Issuing.show',
                'parent_link_id' => 3,
                'display_status' => 0,
            ],
            [
                'id' => 36,
                'link_name' => 'Return Issued Books',
                'slug_name' => 'IssuingDelete',
                'parent_link_id' => 3,
                'display_status' => 0,
            ],

            // Borrowing of Books
            [
                'id' => 37,
                'link_name' => 'Room Use Books',
                'slug_name' => 'Borrowing.index',
                'parent_link_id' => 3,
                'display_status' => 1,
            ],
            [
                'id' => 38,
                'link_name' => 'Add Borrowing Of Books',
                'slug_name' => 'Borrowing.store',
                'parent_link_id' => 3,
                'display_status' => 0,
            ],
            [
                'id' => 39,
                'link_name' => 'Edit Borrowing Of Books',
                'slug_name' => 'Borrowing.show',
                'parent_link_id' => 3,
                'display_status' => 0,
            ],
            [
                'id' => 40,
                'link_name' => 'Returned Borrowed Books',
                'slug_name' => 'BorrowingDelete',
                'parent_link_id' => 3,
                'display_status' => 0,
            ],
            [
                'id' => 41,
                'link_name' => 'Penalty Settings',
                'slug_name' => 'ManagePenalty.index',
                'parent_link_id' => 4,
                'display_status' => 1,
            ],
            [
                'id' => 42,
                'link_name' => 'Edit Penalty Settings',
                'slug_name' => 'ManagePenalty.store',
                'parent_link_id' => 4,
                'display_status' => 0,
            ],
            [
                'id' => 43,
                'link_name' => 'Penalty List',
                'slug_name' => 'Penalty.index',
                'parent_link_id' => 4,
                'display_status' => 1,
            ],
            [
                'id' => 44,
                'link_name' => 'Print Penalty',
                'slug_name' => 'Penalty.PDF',
                'parent_link_id' => 4,
                'display_status' => 0,
            ],
            [
                'id' => 45,
                'link_name' => 'My Profile',
                'slug_name' => 'UserProfile.View',
                'parent_link_id' => 5,
                'display_status' => 1,
            ],
            [
                'id' => 46,
                'link_name' => 'Update My Profile',
                'slug_name' => 'UserProfile.UpdateView',
                'parent_link_id' => 5,
                'display_status' => 1,
            ],
            [
                'id' => 47,
                'link_name' => 'Search Books',
                'slug_name' => 'UserProfile.SearchBook',
                'parent_link_id' => 5,
                'display_status' => 0,
            ],
            [
                'id' => 48,
                'link_name' => 'Reserve Books',
                'slug_name' => 'Reserve.main',
                'parent_link_id' => 5,
                'display_status' => 0,
            ],
            [
                'id' => 49,
                'link_name' => 'My Penalty',
                'slug_name' => 'Penalty.My_Penalty',
                'parent_link_id' => 5,
                'display_status' => 1,
            ],
            [
                'id' => 50,
                'link_name' => 'Materials Archives',
                'slug_name' => 'Archives.Materials_List',
                'parent_link_id' => 6,
                'display_status' => 1,
            ],
            [
                'id' => 51,
                'link_name' => 'Users Archives',
                'slug_name' => 'Archives.Users_List',
                'parent_link_id' => 6,
                'display_status' => 1,
            ],
            [
                'id' => 52,
                'link_name' => 'Room Use Archives',
                'slug_name' => 'Archives.Borrowing_List',
                'parent_link_id' => 6,
                'display_status' => 1,
            ],
            [
                'id' => 53,
                'link_name' => 'Borrowing Archives',
                'slug_name' => 'Archives.Issuing_List',
                'parent_link_id' => 6,
                'display_status' => 1,
            ],
            [
                'id' => 54,
                'link_name' => 'Daily Time Record',
                'slug_name' => 'DTR.view',
                'parent_link_id' => 1,
                'display_status' => 1,
            ],
        ];
        
        DB::table('user_links')->insert($data);
    }
}
