<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class UserDetailsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            //1
            [
                'user_id' => '2',
                'image_url' => 'Bangga-Christian Elvin.jpg',
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Christian Elvin',
                'lastname' => 'Bangga',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00525-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '3',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Eugene',
                'lastname' => 'Raynera',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00086-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '4',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Jannielyn',
                'lastname' => 'Etin',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2019-00114-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '5',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Lougen',
                'lastname' => 'Gierza',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2019-00126-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '6',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Ken Zedric',
                'lastname' => 'Cortes',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00342-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '7',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Joymee',
                'lastname' => 'Dionisio',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => 'JDionisio',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '8',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Lessa Anne',
                'lastname' => 'Pascubillo',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00366-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '9',
                'image_url' => 'Llagas-Pauline Jane.png',
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Pauline Jane',
                'lastname' => 'Llagas',
                'middlename' => 'Santos',
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00218-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '10',
                'image_url' => 'Virtusio-Aira Dynielle.jpg',
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Aira Dynielle',
                'lastname' => 'Virtusio',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2019-00422-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '11',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Aira Dynielle',
                'lastname' => 'Virtusio',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2019-00422-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '12',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Quiel Jeremiah',
                'lastname' => 'Cariaso',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00220-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '13',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Ed Mhar',
                'lastname' => 'Apura',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00231-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],
            [
                'user_id' => '14',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Jayson',
                'lastname' => 'Balatong',
                'middlename' => NULL,
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00341-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '15',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Lailynette',
                'lastname' => 'Burton',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00484-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '16',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Charmie',
                'lastname' => 'Cabanela',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00343-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '17',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Joshua',
                'lastname' => 'Capalaran',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00256-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '18',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'John Russel',
                'lastname' => 'Dacanay',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00361-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '19',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Edmon',
                'lastname' => 'Dela Cruz',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00368-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '20',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Erjohn',
                'lastname' => 'Espuerta',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00353-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '21',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Froilan',
                'lastname' => 'Fernandez',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00379-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '22',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Raymond',
                'lastname' => 'Gabito',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00322-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '23',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Jerome',
                'lastname' => 'Jalandoon',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00293-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '24',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Crisologo',
                'lastname' => 'Lapitan',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00315-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],
            [
                'user_id' => '25',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Van',
                'lastname' => 'Laude',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00487-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],
            [
                'user_id' => '26',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Christian',
                'lastname' => 'Lazaro',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00523-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '27',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'David',
                'lastname' => 'Limba',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00299-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '28',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Lenard',
                'lastname' => 'Llacer',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00376-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '29',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Zairanih',
                'lastname' => 'Lumabi',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00349-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '30',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Maglente',
                'lastname' => 'Nerissa',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00330-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '31',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Jamrei',
                'lastname' => 'Manalo',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00328-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '32',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Marcus',
                'lastname' => 'Manuel',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00372-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '33',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Meriel',
                'lastname' => 'Manuel',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00305-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '34',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Jonh Carlo',
                'lastname' => 'Navaja',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00513-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '35',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Jillian',
                'lastname' => 'Pollescas',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00345-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '36',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Mary Grace',
                'lastname' => 'Ragpala',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00354-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '37',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Jasmine',
                'lastname' => 'Rakim',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00260-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '38',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Shailyn',
                'lastname' => 'Sa - an',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00355-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '39',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Jamie',
                'lastname' => 'Samar',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00338-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],
            
            [
                'user_id' => '40',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Aldrin',
                'lastname' => 'Seroje',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00263-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '41',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'John Timothy',
                'lastname' => 'Sescar',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00313-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '42',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Carlito',
                'lastname' => 'Sollano',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00370-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '43',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Bernadette',
                'lastname' => 'Tradio',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2018-00304-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '44',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'John',
                'lastname' => 'Doe',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2017-00342-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => 45,
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'John',
                'lastname' => 'Doe',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2017-00111-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],
           
            [
                'user_id' => 46,
                'image_url' => NULL,
                'course_id' => NULL,
                'gender_id' => 1,
                'firstname' => 'John',
                'lastname' => 'Doe',
                'middlename' => 'Johhny',
                'contact_no' => '09562679248',
                'barangay' => NULL,
                'city' => 'City',
                'zip_code' => '1632',
                'stud_number' => '2018-00123-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],
            
            [
                'user_id' => 47,
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'John',
                'lastname' => 'Doe',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2017-00112-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '48',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'John',
                'lastname' => 'Doe',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2017-00113-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '49',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'John',
                'lastname' => 'Doe',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2017-00114-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '50',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'John',
                'lastname' => 'Doe',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2017-00115-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '51',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'John',
                'lastname' => 'Doe',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2017-00116-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
                
            ],

            [
                'user_id' => '52',
                'image_url' => NULL,
                'course_id' => 1,
                'gender_id' => Null,
                'firstname' => 'Richard',
                'lastname' => 'Gabito',
                'middlename' => NULL,
                'contact_no' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'zip_code' =>NULL,
                'stud_number' => '2020-00000-TG-0',
                'faculty_code' => NULL,
                'employee_number' => NULL,
            ],
        ];
        DB::table('user_details')->insert($data);
    }
}
